## Aliases ##
alias ls="ls $LS_OPTIONS"
alias ll='ls -alF'

# Bundler Commands
alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias bl='bundle list'
alias bp='bundle package'

alias top='top -o cpu'
alias nerd='vim +NERDTree'
alias mnerd='mvim +NERDTree'
