## Aliases ##
alias ls="ls $LS_OPTIONS"
alias ll='ls -alF'
alias psa='ps auxr'

# Bundler Commands
alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias bl='bundle list'
alias bp='bundle package'
alias bo='bundle open'

# Docker
alias dm='docker-machine'
alias dc='docker-compose'

alias top='top -o cpu'
alias nerd='vim -S +NERDTree'
