## Aliases ##
alias ls="ls $LS_OPTIONS"
alias ll='ls -alF'
alias psa='ps auxr'
alias python='python3'

# Bundler Commands
alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias bl='bundle list'
alias bp='bundle package'
alias bo='bundle open'

# Docker
alias d='docker'
alias dm='docker-machine'
alias dc='docker-compose'

# Kubernetes
alias k='kubectl'

alias top='top -o cpu'

# vim
alias nerd='vim +NERDTree -S Session.vim'
alias nnerd='nvim +NERDTree -S Session.vim'
alias fvim='vim -o $(fzf)'
